name: Run Selenium Script

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
    
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests python-dotenv

      - name: Run Selenium script
        run: python script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add nvd_dashboard_data.csv
          git commit -m 'Update NVD dashboard data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
